version: "3.7"

services:
  redis:
    image: redis/redis-stack:latest
    volumes:
      - ./redis:/data/
    ports:
      - 6379:6379
      - 8001:8001
  ray-feast:
    platform: linux/amd64
    shm_size: 2Gb
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./feature_store:/app/feature_store
    ports:
      - 8888:8888
      - 8265:8265
      - 8000:8000
    depends_on:
      - redis
    environment:
      RAY_BACKEND_LOG_LEVEL: "debug"
    command: /bin/bash

